### ISSUE TITLE
Project TODO list

### ISSUE THREAD

**Issue by beeman** [tabler/tabler-angular#3]
### Navigation

- [ ] `<ui-nav>`, `<ui-nav-item>`, `<ui-nav-brand>`
  - [ ] TS Interfaces 
  - [ ] Demo
  - [ ] Documentation

- [ ] `<ui-sidebar>`, `<ui-sidebar-item>` 
  - [ ] TS Interfaces 
  - [ ] Demo
  - [ ] Documentation

### Forms

- [ ] Integrate formly
  - [ ] Demo
  - [ ] Documentation

### Alerts/Notifications

- [ ] Integrate alerts plugin 
  - [ ] Select plugin
  - [ ] Demo
  - [ ] Documentation

- [ ] Integrate notifications plugin 
  - [ ] Select plugin
  - [ ] Demo
  - [ ] Documentation

**Comment by TotallWAR** [comment]
Is module with chart components in progress?

**Comment by theo4u** [comment]
Is this still the road map @anishbharatha so we ca assist ?
